config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:index, :show, :new, :create] do
    resources :order_items, only: [:create]
    resources :liked_items, only: [:create]
  end
  resources :order_items, only: [:index, :destroy]
  resources :liked_items, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/liked_item.rb
class LikedItem < ApplicationRecord
  belongs_to :user
  belongs_to :product, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :user
  belongs_to :product, dependent: :destroy
  belongs_to :order, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  CATEGORIES = ["T-shirts", "Jeans", "Vestes", "Chaussures", "Jupes", "Pantalons", "Shorts"]
  PRICES = [5, 10, 15, 20, 30, 50]
  COLORS = ["Rouge", "Bleu", "Jaune", "Vert", "Gris", "Blanc", "Noir", "Orange", "Rose"]
  SIZES = ["XS", "S", "M", "L", "XL", "XXL"]
  GENDER = ["Homme", "Femme"]
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :liked_items, dependent: :destroy
  has_many :orders, through: :order_items
  validates :name, presence: true
  validates :category, presence: true
  enum gender: ["femme", "homme"]
  # has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :category , :gender, :price, :color, :size ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :liked_items, dependent: :destroy
  has_many :orders, through: :order_items, source: :product
  has_many :purchased_products, through: :order_items, source: :product
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
   # The callback which stores the current location must be added before you authenticate the user
   # as `authenticate_user!` (or whatever your resource is) will halt the filter chain and redirect
   # before the location can be stored.
   before_action :authenticate_user!

   def after_sign_in_path_for(resource_or_scope)
     stored_location_for(resource_or_scope) || super
   end

   private
     # Its important that the location is NOT stored if:
     # - The request method is not GET (non idempotent)
     # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
     #    infinite redirect loop.
     # - The request is an Ajax request as this can lead to very unexpected behaviour.
     def storable_location?
       request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
     end

     def store_user_location!
       # :user is the scope we are authenticating
       store_location_for(:user, request.fullpath)
     end
end

app/controllers/liked_items_controller.rb
class LikedItemsController < ApplicationController
  def index
    @liked_items = LikedItem.all
    @liked_items = current_user.liked_items
  end

  def create
    @liked_item = LikedItem.new(product: Product.find(params[:product_id]))
    @liked_item.user = current_user

    if @liked_item.save
      redirect_to product_path
    end
  end

  def destroy
    @liked_item = LikedItem.find(params[:id])
    @liked_item.user = current_user

    if @liked_item.destroy
      redirect_to liked_items_path
    end
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
    @order_items = OrderItem.all
    @order_items = current_user.order_items
  end

  def create
    @order_item = OrderItem.new(product: Product.find(params[:product_id]))
    @order_item.user = current_user

    if @order_item.save
      redirect_to product_path(@order_item.product)
    end
  end

  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.user = current_user

    if @order_item.destroy
      redirect_to order_items_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @display_foot = true
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @products = Product.all

    if params[:query].present?
      @products = @products.global_search(params[:query])
    end

    if params[:category].present?
      @products = @products.global_search(params[:category])
    end

    if params[:gender].present?
      @products = @products.where(gender: params[:gender])
    end

    if params[:color].present?
      @products = @products.where(color: params[:color])
    end

    if params[:price].present?
      @products = @products.where(price: params[:price])
    end

    if params[:size].present?
      @products = @products.where(size: params[:size])
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @user = current_user
    @product.user = @user
  end

  def create
    @product = Product.new(product_params)
    @user = current_user
    @product.user = @user

    if @product.save
      redirect_to products_path
    else
      redirect_to order_items_path
    end
  end


  private

  def product_params
    params.require(:product).permit(:name, :price, :category, :description, :gender, :color, :size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FripShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="custom-container mt-70px mb-55px">
      <%= yield %>
    </div>

    <%= render 'shared/footer' if @display_foot %>
  </body>
</html>

app/views/liked_items/index.html.erb
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro laboriosam ratione id, maxime quo nesciunt sit quod in aspernatur cupiditate, aut nostrum, iusto suscipit animi natus. Ad quisquam reiciendis, voluptatibus!</p>

app/views/order_items/index.html.erb
<div class="main-item-container">

  <div class="order-item-container">
    <% @order_items.each do |item| %>
        <div class="order-item-card">
          <!-- <div class="product-photo"> -->
            <%= image_tag "hugoboss.jpg", class: "product-image" %>
          <!-- </div> -->
          <div class="order-item-infos">
            <h3><%= item.product.name %></h3>
            <p><%= item.product.price %>.00 €</p>
            <%= link_to "Supprimer", order_item_path(item), method: :delete, class: "btn btn-blue" %>
          </div>
        </div>
      <% end %>
  </div>

  <div class="payment-card">
    <h4>Titulaire de la carte :</h4>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing, elit. Voluptatibus, enim quia eos! Placeat fuga accusamus, reiciendis vero explicabo, beatae. Facere sed nobis deleniti excepturi eum nisi officia nesciunt quae nemo.</p>
    <h6>Date d'expiration :</h6>
    <br>
    <%= link_to "Paiement", root_path, class: "btn btn-green" %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="search-bar">
  <%= form_tag products_path, method: :get do %>
    <%= text_field_tag :query, params[:query], placeholder: 'Rechercher' %>
    <span></span>
    <%= select_tag :category, options_for_select(Product::CATEGORIES), prompt: "Categories", class: "dropd" %>
    <span></span>
    <%= button_tag type: :submit, class: "search-icon" do %><i class="fas fa-search"></i><% end %>
  <% end %>
</div>


<div class="indexes">
    <%= link_to 'Femmes', products_path(gender: 'femme'), class: "btn btn-blue" %>
    <%= link_to 'Hommes', products_path(gender: 'homme'), class: "btn btn-blue" %>
</div>

app/views/products/index.html.erb
<div class="filter-container">
  <div class="filters">
    <%= form_tag products_path, method: :get do %>
      <%= select_tag :category, options_for_select(Product::CATEGORIES), prompt: "Categories", class: "dropd-filter" %>
      <span></span>
      <%= select_tag :price, options_for_select(Product::PRICES), prompt: "Prix", class: "dropd-filter" %>
      <span></span>
      <%= select_tag :color, options_for_select(Product::COLORS), prompt: "Couleurs", class: "dropd-filter" %>
      <span></span>
      <%= select_tag :size, options_for_select(Product::SIZES), prompt: "Tailles", class: "dropd-filter" %>
      <span></span>
      <%= button_tag type: :submit, class: "search-icon" do %><i class="fas fa-search"></i><% end %>
    <% end %>
  </div>
</div>

<div class="cards-container">
  <% @products.each do |product| %>
    <%= link_to product_path(product) do  %>

      <div class="card-product">

        <div class="product-photo">
          <%= image_tag "hugoboss.jpg", class: "product-image" %>
        </div>

        <div class="like-product">
          <%= link_to product_liked_items_path(product), method: :post, class: "heart" do %>
            <i class="fas fa-heart"></i>
          <% end %>
        </div>

        <div class="card-product-infos">
          <h3><%= product.name %></h3>
          <p><%= product.price %>.00 €</p>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="add-product-container">
  <div class="add-product-card">
      <h4>Ajouter un nouvel article</h4>
      <%= simple_form_for(@product) do |f| %>
      <%= f.input :name, label: "Nom de l'article :" %>
      <%= f.input :price, label: "Prix de l'article :" %>
      <%= f.input :description, label: "Description de l'article :" %>
      <%= f.input :color, label: "Couleur de l'article :" %>

  <div class="dropdown-add">
    <%= select_tag :category, options_for_select(Product::CATEGORIES), prompt: "Categories", class: "dropd" %>
    <%= select_tag :gender, options_for_select(Product::GENDER), prompt: "Genre", class: "dropd" %>
    <%= select_tag :size, options_for_select(Product::SIZES), prompt: "Taille", class: "dropd" %>
    <br>
    <br>
  </div>

  <div class="btn-add">
    <%= f.submit "Ajouter", class: "btn btn-blue" %>
  </div>

    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="product-show-container">

  <div class="return-to-index-show">
    <%= link_to 'Retour', products_path, class: "btn btn-blue" %>
  </div>

  <div class="card-product-show">
    <div class="product-photo">
      <%= image_tag "hugoboss.jpg", class: "product-image" %>
    </div>


    <%= link_to product_liked_items_path(@product), method: :post, class: "heart-show" do %>
      <i class="fas fa-heart"></i>
    <% end %>

  </div>


  <div class="show-card-product-infos">
    <h3><%= @product.name %></h3>
    <p><%= @product.description %></p>
    <p>Couleur : <%= @product.color %></p>
    <p>Taille: <%= @product.size %></p>
    <p><%= @product.price %>.00 €</p>


    <%= link_to "Ajouter au panier", product_order_items_path(@product), method: :post, class: "btn btn-blue" %>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="nav-info">
    <%= link_to "Contact", "#", class: "nav-link" %>
  </div>

  <div class="social-links">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
  </div>

  <div class="nav-info">
    <%= link_to "À Propos", "#", class: "nav-link" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "home" do %>
    <%= image_tag "logo.png", class: "logo" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="info">

        <%= link_to "#", class: "like" do  %>
          <i class="fas fa-heart"></i>
        <% end %>

        <%= link_to order_items_path, class: "cart" do %>
          <i class="fas fa-shopping-bag"></i>
        <% end %>

        <% if user_signed_in? %>
          <% if current_user.order_items.count > 0 %>
            <div class="counter-cart">
              <div id="number">
                <%= current_user.order_items.count %>
              </div>
            </div>
          <% end %>
        <% end %>

        <div class="nav-item dropdown">
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <% if user_signed_in? %>
              <%= link_to "Profil", "#", class: "dropdown-item" %>
              <%= link_to "Mes commandes", "#", class: "dropdown-item" %>
              <%= link_to "Ajouter un article", new_product_path, method: :get, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </div>

  </div>
</div>